spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    include: oauth,jwt,runtime

