spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${root}
    password: ${db-password}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  profiles:
    include: oauth

jwt:
  secret: "SecuritySpringZVBsdksnfBOOTdkwlranjswlahfmrpTwlaksduftlaglrhdqngotjmasterrkehldjdiwlzz"
  header: Authorization
  expiration: 43200
